added shell and shell designation

diff --git a/composite-actions/test-app/action.yaml b/composite-actions/test-app/action.yaml
--- a/composite-actions/test-app/action.yaml
+++ b/composite-actions/test-app/action.yaml
@@ -22,6 +22,7 @@ runs:
         
         ## Build the Service's Devcontainer and wait for pods to spin up (unnecessary when devcontainer up composite action is available)
         - name: Build Devcontainer
+          shell: bash
           run: |
 
             devcontainer up --workspace-folder ${PWD} \
@@ -36,13 +37,13 @@ runs:
             echo $?
 
             # Wait for pods to be ready
-            pod_status=$(k3s kubectl get pods -n payload-app -l app=${{ intputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
-            pod_client_status=$(k3s kubectl get pods -n payload-app -l app=${{ intputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
+            pod_status=$(k3s kubectl get pods -n payload-app -l app=${{ inputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
+            pod_client_status=$(k3s kubectl get pods -n payload-app -l app=${{ inputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
 
             while [[ -z "$pod_status" || "$pod_status" != "Running" ]] || [[ -z "$pod_client_status" || "$pod_client_status" != "Running" ]]; do
                 echo "Checking pod statuses..."
-                pod_status=$(k3s kubectl get pods -n payload-app -l app=${{ intputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
-                pod_client_status=$(k3s kubectl get pods -n payload-app -l app=${{ intputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
+                pod_status=$(k3s kubectl get pods -n payload-app -l app=${{ inputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
+                pod_client_status=$(k3s kubectl get pods -n payload-app -l app=${{ inputs.APP_NAME }} --output=json | jq -r '.items[0].status.phase')
 
                 if [[ -z "$pod_status" || "$pod_status" != "Running" ]] || [[ -z "$pod_client_status" || "$pod_client_status" != "Running" ]]; then
                     echo "One or both pods are not 'Running'. POD: '$pod_status'.  POD_CLIENT_STATUS: '$pod_client_status' ..."
@@ -54,9 +55,9 @@ runs:
         - name: Build Projects
           shell: bash
           run: |
-            [[ ! -f /var/spacedev/tmp/${{ intputs.APP_NAME }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
+            [[ ! -f /var/spacedev/tmp/${{ inputs.APP_NAME }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
             echo "Calculating container name from container_info.json..."
-            DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ intputs.APP_NAME }}/container_info.json '.[0].Name')
+            DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ inputs.APP_NAME }}/container_info.json '.[0].Name')
 
             # Remove the first character if it is a slash
             [[ ${DEV_CONTAINER_NAME:0:1} == "/" ]] && DEV_CONTAINER_NAME="${DEV_CONTAINER_NAME:1}"
@@ -64,17 +65,17 @@ runs:
             echo "Container Name: $DEV_CONTAINER_NAME"
 
             # Build the app
-            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ intputs.APP_NAME }}/src\""
-            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ intputs.APP_NAME }}/src"
+            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ inputs.APP_NAME }}/src\""
+            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ inputs.APP_NAME }}/src"
 
             # Build integrationTestPlugin
-            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ intputs.APP_NAME }}/test/integrationTestPlugin\""
-            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ intputs.APP_NAME }}/test/integrationTestPlugin"
+            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ inputs.APP_NAME }}/test/integrationTestPlugin\""
+            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ inputs.APP_NAME }}/test/integrationTestPlugin"
             echo $?
 
             # Build integrationTests
-            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ intputs.APP_NAME }}/test/integrationTests\""
-            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ intputs.APP_NAME }}/test/integrationTests"
+            echo "Running:  docker exec ${DEV_CONTAINER_NAME} bash -c \"dotnet build /workspaces/${{ inputs.APP_NAME }}/test/integrationTests\""
+            docker exec ${DEV_CONTAINER_NAME} bash -c "dotnet build /workspaces/${{ inputs.APP_NAME }}/test/integrationTests"
             echo $?
 
 
@@ -82,9 +83,9 @@ runs:
           shell: bash
           run: |
 
-            [[ ! -f /var/spacedev/tmp/${{ intputs.APP_NAME }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
+            [[ ! -f /var/spacedev/tmp/${{ inputs.APP_NAME }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
             echo "Calculating container name from container_info.json..."
-            DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ intputs.APP_NAME }}/container_info.json '.[0].Name')
+            DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ inputs.APP_NAME }}/container_info.json '.[0].Name')
 
             # Remove the first character if it is a slash
             [[ ${DEV_CONTAINER_NAME:0:1} == "/" ]] && DEV_CONTAINER_NAME="${DEV_CONTAINER_NAME:1}"
@@ -92,8 +93,8 @@ runs:
             echo "Container Name: $DEV_CONTAINER_NAME"
 
             echo "Starting the integration test host..."
-            echo "Running: docker exec ${DEV_CONTAINER_NAME} bash -c \"/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ intputs.APP_NAME }}\""
-            docker exec ${DEV_CONTAINER_NAME} bash -c "/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ intputs.APP_NAME }}"
+            echo "Running: docker exec ${DEV_CONTAINER_NAME} bash -c \"/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ inputs.APP_NAME }}\""
+            docker exec ${DEV_CONTAINER_NAME} bash -c "/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ inputs.APP_NAME }}"
 
             mkdir -p ${PWD}/.git/logs
             chmod 777 ${PWD}/.git/logs
@@ -101,15 +102,15 @@ runs:
 
             # Execute the app
 
-            echo "Running: k3s kubectl exec -n payload-app deploy/${{ intputs.APP_NAME }} -- bash -c \"/usr/bin/dotnet  /workspaces/${{ inputs.service_name }}/src/bin/Debug/net6.0/${{ inputs.service_name }}.dll\" &"
+            echo "Running: k3s kubectl exec -n payload-app deploy/${{ inputs.APP_NAME }} -- bash -c \"/usr/bin/dotnet  /workspaces/${{ inputs.service_name }}/src/bin/Debug/net6.0/${{ inputs.service_name }}.dll\" &"
             (
                 # Reroute the stdout to a file so we can uniquely identify this run
                 trap "" HUP
                 exec 0< /dev/null
-                exec 1> "${PWD}/.git/logs/${{ intputs.APP_NAME }}.log.stdout"
+                exec 1> "${PWD}/.git/logs/${{ inputs.APP_NAME }}.log.stdout"
                 exec 2>&1
 
-                k3s kubectl exec -n payload-app deploy/${{ intputs.APP_NAME }} -- bash -c "/usr/bin/dotnet  /workspaces/${{ intputs.APP_NAME }}/test/integrationTestHost/bin/Debug/net6.0/integrationTestHost.dll"
+                k3s kubectl exec -n payload-app deploy/${{ inputs.APP_NAME }} -- bash -c "/usr/bin/dotnet  /workspaces/${{ inputs.APP_NAME }}/test/integrationTestHost/bin/Debug/net6.0/integrationTestHost.dll"
             ) &
 
             host_pid=$!
@@ -118,21 +119,21 @@ runs:
             sleep 5
 
             echo "Starting the integration test"
-            echo "Running: docker exec ${DEV_CONTAINER_NAME} bash -c \"/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ intputs.APP_NAME }}-client --disable_plugin_configs\""
-            docker exec ${DEV_CONTAINER_NAME} bash -c "/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ intputs.APP_NAME }}-client --disable_plugin_configs"
+            echo "Running: docker exec ${DEV_CONTAINER_NAME} bash -c \"/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ inputs.APP_NAME }}-client --disable_plugin_configs\""
+            docker exec ${DEV_CONTAINER_NAME} bash -c "/spacefx-dev/debugShim-deploy.sh --debug_shim ${{ inputs.APP_NAME }}-client --disable_plugin_configs"
 
 
             # Executge the integration tests
 
-            echo "k3s kubectl exec -n payload-app deploy/${{ intputs.APP_NAME }}-client -- bash -c \"/usr/bin/dotnet test --verbosity detailed /workspaces/${{ intputs.APP_NAME }}/test/integrationTests/bin/Debug/net6.0/integrationTests.dll --logger \"junit;LogFileName=/workspaces/${{ intputs.APP_NAME }}/.git/test-results.xml\"\" &"
+            echo "k3s kubectl exec -n payload-app deploy/${{ inputs.APP_NAME }}-client -- bash -c \"/usr/bin/dotnet test --verbosity detailed /workspaces/${{ inputs.APP_NAME }}/test/integrationTests/bin/Debug/net6.0/integrationTests.dll --logger \"junit;LogFileName=/workspaces/${{ inputs.APP_NAME }}/.git/test-results.xml\"\" &"
             (
                 # Reroute the stdout to a file so we can uniquely identify this run
                 trap "" HUP
                 exec 0< /dev/null
-                exec 1> "${PWD}/.git/logs/${{ intputs.APP_NAME }}-client.log.stdout"
+                exec 1> "${PWD}/.git/logs/${{ inputs.APP_NAME }}-client.log.stdout"
                 exec 2>&1
 
-                k3s kubectl exec -n payload-app deploy/${{ intputs.APP_NAME }}-client -- bash -c "/usr/bin/dotnet test --verbosity detailed /workspaces/${{ intputs.APP_NAME }}/test/integrationTests/bin/Debug/net6.0/integrationTests.dll --logger \"junit;LogFileName=/workspaces/${{ intputs.APP_NAME }}/.git/test-results.xml\""
+                k3s kubectl exec -n payload-app deploy/${{ inputs.APP_NAME }}-client -- bash -c "/usr/bin/dotnet test --verbosity detailed /workspaces/${{ inputs.APP_NAME }}/test/integrationTests/bin/Debug/net6.0/integrationTests.dll --logger \"junit;LogFileName=/workspaces/${{ inputs.APP_NAME }}/.git/test-results.xml\""
             ) &
 
             client_pid=$!
@@ -148,13 +149,13 @@ runs:
             kill -9 $host_pid
 
             echo "Outputting logs from the integration test host..."
-            cat ${PWD}/.git/logs/${{ intputs.APP_NAME }}.log.stdout
+            cat ${PWD}/.git/logs/${{ inputs.APP_NAME }}.log.stdout
             echo ""
             echo "--------------------"
             echo ""
 
             echo "Outputting logs from the integration test client..."
-            cat ${PWD}/.git/logs/${{ intputs.APP_NAME }}-client.log.stdout
+            cat ${PWD}/.git/logs/${{ inputs.APP_NAME }}-client.log.stdout
             echo ""
             echo "--------------------"
             echo ""
